### ISSUE TITLE
ipinfo.py error

### ISSUE THREAD

**Issue by nicbo05** [N0rz3/TraxOsint#3]
line 18, in look              
    coordinates = {track['loc']}                                                      
                   ~~~~~^^^^^^^                                                       
KeyError: 'loc'                                                   

I am getting this error when running it.

**Comment by nicbo05** [comment]
Another error I found myself with.

Traceback (most recent call last):                                                    
  File "/home/wsn/Desktop/TraxOsint/traxosint.py", line 9, in <module>                
    import main; main.check_version()                                                 
                 ^^^^^^^^^^^^^^^^^^^^                                                 
  File "/home/wsn/Desktop/TraxOsint/main.py", line 11, in check_version               
    asyncio.run(lib.cli.parser())                                                     
  File "/usr/lib/python3.11/asyncio/runners.py", line 190, in run                     
    return runner.run(main)                                                           
           ^^^^^^^^^^^^^^^^                                                           
  File "/usr/lib/python3.11/asyncio/runners.py", line 118, in run                     
    return self._loop.run_until_complete(task)                                        
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                        
  File "/usr/lib/python3.11/asyncio/base_events.py", line 654, in run_until_complete  
    return future.result()                                                            
           ^^^^^^^^^^^^^^^                                                            
  File "/home/wsn/Desktop/TraxOsint/lib/cli.py", line 28, in parser                   
    await ip(Ip)                                                                      
  File "/home/wsn/Desktop/TraxOsint/output/Trax.py", line 25, in ip                   
    ipwhois, coord = await lok(ip)                                                    
                     ^^^^^^^^^^^^^                                                    
  File "/home/wsn/Desktop/TraxOsint/modules/ipwhois.py", line 16, in lok              
    read = await url(ip)                                                              
           ^^^^^^^^^^^^^                                                              
  File "/home/wsn/Desktop/TraxOsint/modules/ipwhois.py", line 13, in url              
    return json.loads(response.text)                                                  
                      ^^^^^^^^^^^^^                                                   
AttributeError: 'NoneType' object has no attribute 'text'
